- become: false
  hosts: all
  name: Converge
  post_tasks:
  - ansible.builtin.copy:
      dest: /tmp/test-message
      mode: 420
      src: test-message
    name: Copy test message into place.
  - changed_when: false
    name: Send an email via mhsendmail.
    shell: cat /tmp/test-message | /opt/mailhog/mhsendmail johndoe@example.com
  - ansible.builtin.uri:
      url: http://localhost:8025/api/v2/messages
    delay: 1
    name: Test retrieiving messages from the MailHog API.
    register: result
    retries: 60
    until: result.status == 200
  pre_tasks:
  - apt: update_cache=true cache_valid_time=600
    name: Update apt cache.
    when: ansible_os_family == 'Debian'
  - ansible.builtin.package:
      name:
      - '@Development tools'
      - tar
      - unzip
      - net-tools
      - curl
      state: present
    name: Ensure build dependencies are installed (RedHat).
    when: ansible_os_family == 'RedHat'
  - ansible.builtin.apt:
      name:
      - build-essential
      - tar
      - unzip
      - net-tools
      - curl
      state: present
    name: Ensure build dependencies are installed (Debian).
    when: ansible_os_family == 'Debian'
  roles:
  - buluma.daemonize
  - ansible-role-mailhog
