---
- name: Converge
  hosts: all
  become: false
  gather_facts: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts['os_family'] == 'Debian'
    - name: Ensure build dependencies are installed (RedHat).
      ansible.builtin.package:
        name:
          - "@Development tools"
          - tar
          - unzip
          - net-tools
          - curl
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
    - name: Ensure build dependencies are installed (Debian).
      ansible.builtin.apt:
        name:
          - build-essential
          - tar
          - unzip
          - net-tools
          - curl
        state: present
      when: ansible_facts['os_family'] == 'Debian'

  roles:
    - role: buluma.daemonize
    - role: buluma.mailhog

  post_tasks:
    - name: Copy test message into place.
      ansible.builtin.copy:
        dest: /tmp/test-message
        mode: "0644"
        src: test-message
    - name: Send an email via mhsendmail.
      ansible.builtin.shell:
        cmd: cat /tmp/test-message | /opt/mailhog/mhsendmail johndoe@example.com
      changed_when: false
    - name: Test retrieiving messages from the MailHog API.
      ansible.builtin.uri:
        url: http://localhost:8025/api/v2/messages
      delay: 1
      register: result
      retries: 60
      until: result.status == 200
